import { Router, type IRouter } from "express";

const router: IRouter = Router();

export const MODELS = [
  // ─── IMAGE GENERATION ──────────────────────────────────────────────────────
  {
    id: "fal-ai/nano-banana-2",
    name: "Nano Banana 2",
    provider: "Google",
    category: "image",
    type: "text-to-image",
    description: "Google's Imagen 3 model. Photorealistic images with excellent prompt adherence. Upload up to 14 reference images.",
    tags: ["photorealistic", "fast", "commercial"],
    supportsDuration: false, supportsImageInput: true, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 14,
    maxDuration: null,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    voices: [],
  },
  {
    id: "fal-ai/nano-banana-pro",
    name: "Nano Banana Pro",
    provider: "Google",
    category: "image",
    type: "text-to-image",
    description: "Google's premium Imagen model. Enhanced detail, realism, and superior image quality. Up to 14 reference images.",
    tags: ["photorealistic", "professional", "high-quality"],
    supportsDuration: false, supportsImageInput: true, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 14,
    maxDuration: null,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    voices: [],
  },
  {
    id: "fal-ai/flux/schnell",
    name: "FLUX Schnell",
    provider: "Black Forest Labs",
    category: "image",
    type: "text-to-image",
    description: "FLUX's fastest model. Generates high-quality images in under 2 seconds. Great for rapid iteration.",
    tags: ["fast", "flux", "open-source"],
    supportsDuration: false, supportsImageInput: false, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4", "21:9"],
    voices: [],
  },
  {
    id: "fal-ai/flux-pro",
    name: "FLUX Pro",
    provider: "Black Forest Labs",
    category: "image",
    type: "text-to-image",
    description: "FLUX's flagship model. State-of-the-art image quality with superior prompt following and detail.",
    tags: ["professional", "flux", "detail"],
    supportsDuration: false, supportsImageInput: true, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4", "21:9"],
    voices: [],
  },
  {
    id: "fal-ai/recraft-v3",
    name: "Recraft V3",
    provider: "Recraft",
    category: "image",
    type: "text-to-image",
    description: "Top-ranked image model on HuggingFace. Exceptional typographic rendering and vector-style imagery.",
    tags: ["typography", "design", "vector"],
    supportsDuration: false, supportsImageInput: true, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3"],
    voices: [],
  },
  {
    id: "fal-ai/ideogram/v2",
    name: "Ideogram V2",
    provider: "Ideogram",
    category: "image",
    type: "text-to-image",
    description: "Unmatched text rendering inside images. Perfect for posters, logos, and graphics.",
    tags: ["text-in-image", "posters", "design"],
    supportsDuration: false, supportsImageInput: true, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3"],
    voices: [],
  },

  // ─── TEXT TO VIDEO ──────────────────────────────────────────────────────────
  {
    id: "fal-ai/kling-video/v3/pro/text-to-video",
    name: "KLING 3.0 Pro",
    provider: "Kuaishou",
    category: "video",
    type: "text-to-video",
    description: "KLING's most advanced video model. Cinematic quality with precise motion and multi-shot video.",
    tags: ["cinematic", "high-quality", "motion", "audio"],
    supportsDuration: true, supportsImageInput: false, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: 15,
    aspectRatios: ["16:9", "9:16", "1:1"],
    voices: [],
  },
  {
    id: "fal-ai/veo3",
    name: "VEO 3.1",
    provider: "Google DeepMind",
    category: "video",
    type: "text-to-video",
    description: "Google DeepMind's flagship video model. Realistic physics, natural motion, and native audio.",
    tags: ["realistic", "physics", "google", "audio"],
    supportsDuration: true, supportsImageInput: false, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: 8,
    aspectRatios: ["16:9", "9:16", "1:1"],
    voices: [],
  },
  {
    id: "fal-ai/sora-2/text-to-video",
    name: "Sora 2",
    provider: "OpenAI",
    category: "video",
    type: "text-to-video",
    description: "OpenAI's Sora 2 with exceptional scene understanding, temporal coherence and built-in audio.",
    tags: ["openai", "temporal", "scene", "audio"],
    supportsDuration: true, supportsImageInput: false, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: 10,
    aspectRatios: ["16:9", "9:16", "1:1"],
    voices: [],
  },
  {
    id: "fal-ai/wan/v2.2-a14b/text-to-video",
    name: "Wan 2.2",
    provider: "Alibaba",
    category: "video",
    type: "text-to-video",
    description: "Alibaba's Wan 2.2 open-source video model. High quality motion with fast inference times.",
    tags: ["open-source", "fast", "alibaba"],
    supportsDuration: true, supportsImageInput: false, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: 10,
    aspectRatios: ["16:9", "9:16", "1:1"],
    voices: [],
  },

  // ─── IMAGE TO VIDEO ─────────────────────────────────────────────────────────
  {
    id: "fal-ai/kling-video/v3/pro/image-to-video",
    name: "KLING 3.0 (Фото→Видео)",
    provider: "Kuaishou",
    category: "video",
    type: "image-to-video",
    description: "Animate any image. Upload a start frame and optionally an end frame — KLING will generate the motion between them.",
    tags: ["image-to-video", "animation", "motion", "start-end-frame"],
    supportsDuration: true, supportsImageInput: true, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: true, maxReferenceImages: 0,
    maxDuration: 10,
    aspectRatios: ["16:9", "9:16", "1:1"],
    voices: [],
  },
  {
    id: "fal-ai/sora-2/image-to-video",
    name: "Sora 2 (Фото→Видео)",
    provider: "OpenAI",
    category: "video",
    type: "image-to-video",
    description: "Animate images into videos using OpenAI's Sora 2. Maintains visual fidelity while adding natural motion.",
    tags: ["openai", "image-to-video", "animation"],
    supportsDuration: true, supportsImageInput: true, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: 10,
    aspectRatios: ["16:9", "9:16", "1:1"],
    voices: [],
  },
  {
    id: "fal-ai/wan/v2.2-a14b/image-to-video",
    name: "Wan 2.2 (Фото→Видео)",
    provider: "Alibaba",
    category: "video",
    type: "image-to-video",
    description: "Animate any image using Alibaba's Wan 2.2 model. Fast and high quality results.",
    tags: ["open-source", "image-to-video", "fast"],
    supportsDuration: true, supportsImageInput: true, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: 10,
    aspectRatios: ["16:9", "9:16", "1:1"],
    voices: [],
  },

  // ─── MOTION CONTROL ─────────────────────────────────────────────────────────
  {
    id: "fal-ai/kling-video/v3/pro/motion-control",
    name: "KLING Motion 3.0 Pro",
    provider: "Kuaishou",
    category: "motion-control",
    type: "motion-control",
    description: "Transfer realistic motion from a reference video to a character image. Upload both and KLING copies the motion.",
    tags: ["motion-transfer", "reference-video", "character", "animation"],
    supportsDuration: false, supportsImageInput: true, supportsVideoInput: true, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: [],
    voices: [],
  },
  {
    id: "fal-ai/kling-video/v3/standard/motion-control",
    name: "KLING Motion 3.0 Standard",
    provider: "Kuaishou",
    category: "motion-control",
    type: "motion-control",
    description: "Cost-effective motion transfer. Perfect for portraits and simple animations. Supports up to 30s videos.",
    tags: ["motion-transfer", "reference-video", "portrait", "cost-effective"],
    supportsDuration: false, supportsImageInput: true, supportsVideoInput: true, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: [],
    voices: [],
  },

  // ─── LIP SYNC ───────────────────────────────────────────────────────────────
  {
    id: "fal-ai/sync-lipsync",
    name: "Sync Labs Lipsync",
    provider: "Sync Labs",
    category: "lipsync",
    type: "lipsync",
    description: "Industry-leading lip sync. Upload any face video and audio to generate perfectly synced lip movements.",
    tags: ["lipsync", "sync", "professional"],
    supportsDuration: false, supportsImageInput: false, supportsVideoInput: true, supportsAudioInput: true,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: [],
    voices: [],
  },
  {
    id: "fal-ai/sync-lipsync/v2",
    name: "Sync Labs Lipsync v2",
    provider: "Sync Labs",
    category: "lipsync",
    type: "lipsync",
    description: "Latest version. Higher fidelity facial animations and improved stability.",
    tags: ["lipsync", "sync", "v2", "high-fidelity"],
    supportsDuration: false, supportsImageInput: false, supportsVideoInput: true, supportsAudioInput: true,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: [],
    voices: [],
  },

  // ─── TEXT TO SPEECH ─────────────────────────────────────────────────────────
  {
    id: "fal-ai/f5-tts",
    name: "F5-TTS",
    provider: "SWivid",
    category: "tts",
    type: "text-to-speech",
    description: "Zero-shot voice cloning TTS. Upload a reference audio clip and replicate any voice. Supports 20+ languages.",
    tags: ["voice-cloning", "multilingual", "zero-shot"],
    supportsDuration: false, supportsImageInput: false, supportsVideoInput: false, supportsAudioInput: true,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: [],
    voices: ["default"],
  },
  {
    id: "fal-ai/tada/3b/text-to-speech",
    name: "TADA 3B TTS",
    provider: "fal.ai",
    category: "tts",
    type: "text-to-speech",
    description: "High-quality TTS with natural prosody. 3B parameter model with expressive voice generation.",
    tags: ["natural", "expressive", "high-quality"],
    supportsDuration: false, supportsImageInput: false, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: [],
    voices: ["default"],
  },
  {
    id: "fal-ai/tada/1b/text-to-speech",
    name: "TADA 1B TTS",
    provider: "fal.ai",
    category: "tts",
    type: "text-to-speech",
    description: "Fast and lightweight TTS. 1B parameter model for quick audio generation.",
    tags: ["fast", "lightweight", "tts"],
    supportsDuration: false, supportsImageInput: false, supportsVideoInput: false, supportsAudioInput: false,
    supportsEndFrame: false, maxReferenceImages: 0,
    maxDuration: null,
    aspectRatios: [],
    voices: ["default"],
  },
];

router.get("/models", (_req, res) => {
  res.json({ models: MODELS });
});

export default router;
